### ISSUE TITLE
Add toJSON property to HookContext

### ISSUE THREAD

**Issue by reggaedit** [feathersjs-ecosystem/feathers-typescript#19]
Hook contexts appear to have a toJSON() property, which can sometimes be a function and sometimes not according to [this example](https://github.com/feathersjs/feathers-chat/blob/master/src/hooks/logger.js):
```js
if(typeof context.toJSON === 'function') {
      logger.debug('Hook Context', JSON.stringify(context, null, '  '));
}
```

When I type it up I get an error saying "[ts] Property 'toJSON' does not exist on type 'HookContext<any>'."

See here: https://github.com/feathersjs/commons/blob/master/lib/hooks.js#L11
and here: https://github.com/feathersjs/commons/blob/master/CHANGELOG.md#v130-2017-11-20

Also found this, the FeathersError object also seems to have the toJSON property
https://github.com/feathersjs/errors/blob/master/lib/index.js#L69

Does this need to be added?

Cheers,
David

**Comment by dobeerman** [comment]
Does any changes? I still getting this error.

**Comment by j2L4e** [comment]
Could you provide a PR over here? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/feathersjs__feathers thanks :)

**Comment by daffl** [comment]
Closing since it this should be fixed in v4 and TypeScript issues should now be reported at https://github.com/feathersjs/feathers
