### ISSUE TITLE
Fix service method types to handle pagination

### ISSUE THREAD

**Issue by murbanowicz** [feathersjs-ecosystem/feathers-typescript#20]
At the moment we have:
```
export interface ServiceMethods<T> {
    find(params?: Params): Promise<T[] | Paginated<T>>;
```

however, it does not work properly as by default TS sees it as T[] which enforce to use (result as Paginated<service>).

I thought about some change to handle it better but so far I cannot figure it out.
Any ideas to make it work with both paginated enabled and disabled?

**Comment by daffl** [comment]
Closing since it this should be fixed in v4 and TypeScript issues should now be reported at https://github.com/feathersjs/feathers
