### ISSUE TITLE
Please add demo of how to install these typings in README

### ISSUE THREAD

**Issue by freewind** [feathersjs-ecosystem/feathers-typescript#22]
After a long time of searching, I finally know how to install the typings, from a long discussion of [a github issue](https://github.com/feathersjs/feathers/issues/381)

Say: 

```
import feathers from '@feathersjs/feathers'
```

We should install `npm install -D @types/feathersjs__feathers`.

It will be great if we could add this kind demo to README.

**Comment by daffl** [comment]
I might be wrong here but that's how I install any typings that are shipped via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/)?

**Comment by freewind** [comment]
I mean the name conversion, use double underscore. I'm quite new to typescript, not know there is such rule, so I think it will be great to address it in REAMDE, for someone who is not so familiar with this.

**Comment by j2L4e** [comment]
It's the usual naming of typings for scoped packages. But i can see the need for documentation here.

**Comment by daffl** [comment]
Maybe we should still add them as dependencies in the repositories like we talked about before?

**Comment by freewind** [comment]
I still found it really hard to check if there is a typing lib for a featherjs lib. Today I want find one for `feathers-nedb`, and I've tried:

1. `@types/feathers-nedb`, `@types/feathersjs-nedb`
2. `@types/feathers__nedb`, `@types/feathersjs__nedb`

Since there are some places use the name `feathers`, and some else uses `feathersjs`, so I have to try both.

I didn't find one, so,

3. I go to <https://github.com/feathersjs-ecosystem/feathers-nedb>, but there is no information about typing.
4. I go back to this project, and in the readme, there is a link to the issue <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22805>, with the title "Add definitions for 16 packages of the @feathersjs scope". But the 16 packages are not list, so I have to find what are they. I search for `featherjs` on npmjs, but there result is much more than 16, and I don't know what to do next.

So finally I'm still not sure if there is typings for feathers-nedb.

You have done so many great things for feathers, but as new to feathersjs, I found it not quite easy to get the information about typings.

What about adding a list in the readme, to show the typings for the libs? e.g.

- `feathers-express`: `npm install -D @types/feathers__express`
- `feathers-others`: `npm install -D @types/feathers__others`
- `feathers-nedb`: no typings yet

So anyone searches to this repo, can find the information in one second

**Comment by daffl** [comment]
It's because `feathers-nedb` is _not_ in the `@feathersjs` scope. Outside of the `@feathersjs` scope is up to each individual module to supply typings.

**Comment by freewind** [comment]
Thanks and you're right. Anyway, I just switched to other options, so I'm closing this issue

**Comment by daffl** [comment]
Side note, the [Feathers Plus CLI](https://generator.feathers-plus.com/) generates a TypeScript Feathers applications (with optional GraphQL and schema integration) and everything installed properly.
