### ISSUE TITLE
Feathers Express app.use() fails when passing service AND middleware functions

### ISSUE THREAD

**Issue by SteffenLanger** [feathersjs-ecosystem/feathers-typescript#26]
When creating a typed feathers express application like so:
```javascript
import {Application} from "@feathersjs/express";
import express from '@feathersjs/express';
import feathers from '@feathersjs/feathers';

interface ServiceTypes {
}

const app: Application<ServiceTypes> = express(feathers());
```

I get the error `TS2345: Argument of type '"/reports/:reportId/photoFiles"' is not assignable to parameter of type 'RequestHandlerParams'.` for the first parameter (route url).
The URL is not the problem, though, because the URL is not marked incorrect anymore as soon as I change `new PhotoS3Service()` to `new PhotoS3Service() as any`.

```javascript
app.use("/reports/:reportId/photoFiles",
    // context.params.cache will be populated
    readCacheHeaders('If-None-Match'),
    // Make the field "photo" available at feathers.params.uploadedFile.
    enableFileUpload({
        fieldName : 'photo'
    }),
    // The service itself
    new PhotosS3Service(),
    // Determine the right content type, especially in the case when there is a buffer object
    sendBuffer()
);
```

The issue is caused by `app.use` not being overwritten by feathers' typings. Express expects a function signature like `(req, res, next) => any` so it cannot handle the service instance resulting from `new PhotosS3Service()`.

According to the documentation [app.use() should accept a service object](https://docs.feathersjs.com/api/express.html#appusepath-servicemwmw).

I am willing to provide a pull request with an overloaded function declaration as soon as a maintainer states that it makes sense ;)

**Comment by daffl** [comment]
If you have a look at the [@feathersjs/express documentation](https://docs.feathersjs.com/api/express.html) you can see that an application should be instantiated like this:

```ts
import feathers from '@feathersjs/feathers';
import express from '@feathersjs/express';

// Create an app that is a Feathers AND Express application
const app = express(feathers());
```

**Comment by SteffenLanger** [comment]
You're absolutely right and that's what I do. I just wanted to name the types. I'll edit the request to show the actual code.

**Comment by SteffenLanger** [comment]
@daffl, could you maybe have a look at the updated code?

Since this would be my first contribution for feathers' Typescript definitions, I would like to get a statement from a core maintainer before getting to work. Thanks!

**Comment by SteffenLanger** [comment]
Sorry to bother you, @daffl. Could you give me a hint on this? If there is someone else who could let me know if this makes sense, please let me know.

**Comment by daffl** [comment]
What do you need? `Application.use` probably needs to be overwritten with something like `... express.RequestHandler|Service<T>` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/feathersjs__express/index.d.ts

**Comment by j2L4e** [comment]
You're right, it does make sense. 

express.use and feathersApp.use are merged here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ca809fa16fdb3f3c908bac411b0204c501ae71be/types/feathersjs__express/index.d.ts#L14

it'd rather need to look like this: 
```
export interface Application<T> extends express.Application, FeathersApplication<T> {
  use: // some proper overload
}
```

**Comment by SteffenLanger** [comment]
I opened a pull request for a possible solution at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34782.

I'll close this issue as soon as the pull request is merged.

**Comment by daffl** [comment]
Could you add it to https://github.com/feathersjs/feathers/blob/master/packages/express/index.d.ts as well? This is where things will live going forward. Thanks!

**Comment by SteffenLanger** [comment]
Sure! I created a pull request at https://github.com/SteffenLanger/feathers/pull/1.

**Comment by SteffenLanger** [comment]
Sure! I created a pull request at https://github.com/feathersjs/feathers/pull/1292.

**Comment by deskoh** [comment]
With the typings you provided, I'm getting the following errors with code snippet below. The error is due to the `setup` method. Adding `implements SetupMethod` explicitly doesn't help either. In fact, this was introduced with `@types/feathersjs__express` @ `1.1.6` with the similar type definitions.

```TypeScript
class MessageService implements Partial<ServiceMethods<any>> {
    public setup (app: App, path: string): void {
    }
    public async find(params?: Params): Promise<any[]> {
      return []
    }
}
app.use('/', new MessageService());
```

```
Argument of type '"/"' is not assignable to parameter of type 'RequestHandlerParams'.ts(2345)
```

**Comment by deskoh** [comment]
Extending the union type with `Partial<ServiceMethods<T> & SetupMethod>` seemed to work:

```TypeScript
export interface FeathersRouterMatcher<T> {
    (path: PathParams, ...handlers: Array<(RequestHandler | RequestHandlerParams | Partial<ServiceMethods<T> & SetupMethod> | Partial<ServiceMethods<any> & SetupMethod> | Application)>): T;
}
```

**Comment by SteffenLanger** [comment]
@deskoh, does changing `Partial<ServiceMethods<any> & SetupMethod>` to `Partial<ServiceMethods<T> & SetupMethod>` do the trick? I think that T is any if no T is given, so that should work, too.

This would be the result then:
```typescript
export interface FeathersRouterMatcher<T> {
    (path: PathParams, ...handlers: Array<(RequestHandler | RequestHandlerParams | Partial<ServiceMethods<T> & SetupMethod> | Partial<ServiceMethods<any> & SetupMethod> | Application)>): T;
}
```

**Comment by deskoh** [comment]
@SteffenLanger Figured out a workaround in usage. Issue is quite tricky. See code below.

```ts
import feathers, { Application as FeathersApplication, ServiceMethods, SetupMethod } from '@feathersjs/feathers';
import feathersExpress, * as express from '@feathersjs/express';
import { Application } from '@feathersjs/express';

type ServiceType = { messages: any };

type ExpressAndFeathersApp = Application<ServiceType>;
type FeathersApp = FeathersApplication<ServiceType>;

const app: ExpressAndFeathersApp = feathersExpress(feathers());

class MessageService implements Partial<ServiceMethods<ServiceType>>, SetupMethod {
    // Code below working with existing typings [`@types/feathersjs__express 1.1.5`] but will break with proposed typings.
    // public setup (app: ExpressAndFeathersApp, path: string): void {
    // }

    // `app` need to be of type `FeathersApp` instead
    public setup (app: FeathersApp, path: string): void {
    }

    public async find(params?: any): Promise<any[]> {
      return []
    }
}
app.use('/', new MessageService());
```

**Comment by SteffenLanger** [comment]
The issue is that the type `Partial<ServiceMethods<T> & SetupMethod>` within `IFeathersRouteMatcher<T>` expects a `setup` method when matching even though the TypeScript interface is wrapped with `Partial`. This should make every property optional.
I suppose that for matching overloaded types, optional properties are still considered required. Maybe this is a feature to allow for more complex matching algorithms. If this was not the case, an interface wrapped in `Partial` would probably match too quickly and would thus prevent other more precise overloaded definitions from being chosen.

This is something I could imagine to solve this issue: Match both applications with and without a `SetupMethod`.
```typescript
export interface IFeathersRouterMatcher<T> {
    (path: PathParams, ...handlers: (RequestHandler | RequestHandlerParams | Partial<ServiceMethods<T>> | Partial<ServiceMethods<T> & SetupMethod> | Application)[]): T;
}
```

**Comment by deskoh** [comment]
It is optional, but if `setup` method is defined, the defined `setup` method has to be compatible.
Why not drop `SetupMethod` completely? Unless there is a case where we want to match an object where only `the setup` method and none of the Service Methods are defined.

```ts
export interface IFeathersRouterMatcher<T> {
    (path: PathParams, ...handlers: (RequestHandler | RequestHandlerParams | Partial<ServiceMethods<T>> | Application)[]): T;
}
```

**Comment by daffl** [comment]
Closing since it this should be fixed in v4 and TypeScript issues should now be reported at https://github.com/feathersjs/feathers
