### ISSUE TITLE
Hook typing should include optional "next" callback as a valid argument

### ISSUE THREAD

**Issue by leedongwei** [feathersjs-ecosystem/feathers-typescript#28]
Using `next` as a callback for a hooks is valid (but undocumented in docs.feathersjs.com). 

It's implementation is found [here](https://github.com/feathersjs/feathers/blob/b33fbcc3634fea6a7aee854d77147bdbfb246801/packages/commons/lib/hooks.js#L135), and one usage example is [here](https://github.com/eddyystop/feathers-hooks-validate-joi/blob/064890339d801754ad1d17522c04abf92de42cf3/index.js#L10).

**Comment by daffl** [comment]
The `next` callback should not be used anymore and will be replaced with different functionality in the future.
