### ISSUE TITLE
Property 'secret' does not exist on type 'FeathersAutheticationOptions'

### ISSUE THREAD

**Issue by frankeros** [feathersjs-ecosystem/feathers-typescript#30]
The type 'FeathersAutheticationOptions' from @types/feathersjs__authentication does not have the property 'secret', so ts not compile when you try to set 

`app.configure(authentication( { secret: 'supersecret' } ); `

and if you try to omit this property you get the message 'You must provide a 'secret' in your authentication configuration'.
Even if you added this property in the config file.

I can resolve this with the next approach:
```
import authentication, { FeathersAuthenticationOptions } from '@feathersjs/authentication';
...
const options: FeathersAuthenticationOptions = {};
Object.defineProperty(options, 'secret', {
    value: 'supersecret',
    enumerable: true
};


app.configure(authentication(options));
```
It would be nice if it is added for the next release
Thanks

**Comment by daffl** [comment]
Closing since it is fixed in v4 and TypeScript issues should now be reported at https://github.com/feathersjs/feathers
