### ISSUE TITLE
Move definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by erikma** [feathersjs-ecosystem/feathers-typescript#7]
This repo is not building anything and there are no NPM packages published from it that I can see. It seems wiser to let DefinitelyTyped take up the build, tslint triggers, and publishing burden by moving these definitions there.

**Comment by daffl** [comment]
That is the plan, someone just needs to make it happen. @j2L4e is too busy right now but can definitely point anybody willing to continue his work in the right direction.

**Comment by erikma** [comment]
I'll try to carve out some time in the next week or so. I'd like to get to Feathers 3 but regressing on type defs is a non-starter given the strength of the V2 .d.ts files

**Comment by j2L4e** [comment]
This repo is now obsolete. I moved everything to a dt fork last night. PR is pending: definitelytyped/definitelytyped#22805

**Comment by daffl** [comment]
This is go great! Should we keep this repo around to log issues/questions related to TS?

**Comment by j2L4e** [comment]
I'm afraid people wont find it but let's give it a try

**Comment by erikma** [comment]
Thanks for moving on this - looking forward to getting rid of the red squiggles in my v3 conversion! I reviewed (not official since I'm online a sometime contributor) on DT. I'd recommend just letting those commits be the official record and kill this repo once all info here has moved. Otherwise this repo just clutters the historical record and burdens you with questions like mine. P)

**Comment by eakarpov** [comment]
@erikma Would types be able to be downloaded via @types/feathers-client? If so, when we should expect this to happen? Thanks.

**Comment by erikma** [comment]
The others on this thread can provide confirmation - for Feathersjs 3 the completion of the related DefinitelyTyped commits would soon after result in @types/@featthers/feathers and related @types/@feathers/* NPM packages that would let you import those definitions alongside feathersjs 3.

**Comment by j2L4e** [comment]
It'll be `@types/feathersjs__feathers` which is a TypeScript/DT limitation on scoped packages...

**Comment by j2L4e** [comment]
DefinitelyTyped/DefinitelyTyped#22805 was merged and typings for the @feathersjs scoped packages are available by installing `@types/feathersjs__package`

**Comment by eakarpov** [comment]
@j2L4e Excellent, thank you! I will use it soon.
