### ISSUE TITLE
[@types/feathersjs__express] export .notFound(), .errorHandler()...

### ISSUE THREAD

**Issue by HelloEdit** [feathersjs-ecosystem/feathers-typescript#8]
Hello !

The definitions of feathersjs__express does not export the latest express definitions.

https://user-images.githubusercontent.com/25421857/35121573-29fe862e-fc9c-11e7-90c9-50d02eb6ece1.png

**Comment by j2L4e** [comment]
They do.

Use 

`import { notFound, errorHandler } from '@feathersjs/express'`

**Comment by HelloEdit** [comment]
Or you can do this like this:

```
import * as express from '@feathersjs/express'

const app = express.default(feathers())

app.use(express.notFound())
app.use(express.errorHandler({ logger }))
```

But `.json()` and `.urlencoded()` are not exported in the definitions:

![image](https://user-images.githubusercontent.com/25421857/35481229-da5ba7c4-041f-11e8-8851-90797b7c70c4.png)

**Comment by j2L4e** [comment]
Yeah, TS doesn't handle complete CommonJS reexports very well. Generally, feathers' module structure isn't that well-suited for TS.

You have several options:

The package reexports the express package as { original }.
`express.original.urlencoded` and `express.original.json`

I'd just import from the express package directly `import { urlencoded, json } from 'express'`. There's virtually no difference.

Are you using the auto import plugin for VS Code?

**Comment by HelloEdit** [comment]
vz So if I understand correctly, it is necessary to make modifications on the code so that typescript takes into account `urlencoded` and `json`? There is no solution for it to be exported normally and works like `errorHandler` and `notFound`?

**Comment by j2L4e** [comment]
I added the reexports now. We need to manually keep track of changes to the express exports now. Not that pretty...

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23230
