### ISSUE TITLE
Feathers Buzzard typings issue

### ISSUE THREAD

**Issue by sinedied** [feathersjs-ecosystem/feathers-typescript#9]
Hello, I am in the process of migrating from Feathers v2 to v3 and I have some typings issue (the app was already in typescript, nothing changed regarding this).

I followed the migration guide and added the new typing packages:
```ts
    "@types/feathersjs__errors": "^3.2.0",
    "@types/feathersjs__express": "^1.1.2",
    "@types/feathersjs__feathers": "^3.0.0",
```
But I have strange typings error which I do not understand, as when I looked in the `.d.ts` files everything seemed correct.

This are the errors:
```
Error:(18, 20) TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/noda/Desktop/facilityhero/service-starter/node_modules/@types/feathersjs__express/...' has no compatible call signatures.
Error:(18, 28) TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/noda/Desktop/facilityhero/service-starter/node_modules/@types/feathersjs__feathers...' has no compatible call signatures.
```

and the code, the error being on the app definition line:
```ts
import config = require('config');
import path = require('path');
import favicon = require('serve-favicon');
import compress = require('compression');
import helmet = require('helmet');
import cors = require('cors');
import feathers = require('@feathersjs/feathers');
import express = require('@feathersjs/express');
import swagger = require('feathers-swagger');
import expressWinston = require('express-winston');
import notFoundHandler = require('feathers-errors/not-found');

import { logger } from './core/logger';
import { appInsightsRequestTracker } from './middleware/app-insights';
import { middleware } from './middleware';
import { services } from './services';

export const app = express(feathers());  // <-- error
...
```

I also tried to changed the imports to `import * as feathers from '@feathersjs/feathers';` and the result is the same.

Here is my `tsconfig.json`:
```
{
  "compilerOptions": {
    "lib": ["es6"],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6",
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true
  }
}
```

Is there anything wrong?
Everything was working fine prior to the v3 migration with internal typings.
Note that I am using `typescript@2.6.2`.

Thanks for your help

**Comment by sinedied** [comment]
Sorry, it seems the problem was (again) with npm: deleting `node_modules` and running `npm install` agains fixed it 😞

**Comment by j2L4e** [comment]
I'd actually be surprised if this had fixed your problem. The v3 typings use the ES module default export rather than the commonJS default export. This means that you need to import the default callable like this:

```
import feathers from '@feathersjs/feathers'; // equals import { default as feathers } from '@feathersjs/feathers'
import express from '@feathersjs/express'; // equals import { default as express } from '@feathersjs/express'
```

Sorry for the lack of documentation here. I haven't found the time to put something together.

**Comment by sinedied** [comment]
@j2L4e Thanks, actually I don't know why the error went away for some time, as it came back again a few hours later ^^

That fixed the app typings issue, but now I have some typings issue with feathers/express like
```
  .use(express.json())
  .use(express.urlencoded({ extended: true }))
```

from the typings I understand that I can do `import { json, urlencoded } from '@feathersjs/express` but that would be simpler to extend the typings to keep compatibility with the "normal" syntax.

**Comment by j2L4e** [comment]
Unfortunately right now you can't get both :( Choose one of these:

```
import feathers from '@feathersjs/feathers'; // equals import { default as feathers } from '@feathersjs/feathers'
import express, { json, urlencoded } from '@feathersjs/express'; // equals import { default as express } from '@feathersjs/express'

export const app = express(feathers());

app.use(json())
app.use(urlencoded({ extended: true }))
```

or

```
import feathers from '@feathersjs/feathers';
import * as express from '@feathersjs/express';

export const app = express.default(feathers());

app.use(express.json())
app.use(express.urlencoded({ extended: true }))
```

**Comment by sinedied** [comment]
I went with the latter, thanks
